### ISSUE TITLE
Finish Travolta, the Facebook bot

### ISSUE THREAD

**Issue by crcastle** [heroku/dreamhouse-disco-old#21]

**Comment by thejonanshow** [comment]
Shipped these features today:
- [x] Create Disco Registrations
- [x] Disco Registrations have unique room names
- [x] Disco Registrations have auth tokens
- [x] Outgoing song requests include auth tokens
- [x] Require room name on incoming Facebook messages
- [x] Reply to Facebook users with list of rooms when message does not include room name

Outstanding:
- [x] Get Facebook user's name/email and include in song requests to Disco instead of sender ID
- [x] Background job to delete inactive registrations, apps that don't respond to a ping per minute for 5 minutes.

**Comment by thejonanshow** [comment]
This is all shipped to staging and production. You should be able to receive messages for any app that sends a Disco registration now.

Both of those databases have been dropped and I haven't been able to get dreamhouse-disco-staging or production to send another registration request. You should help me get jonan-dreamhouse-disco configured tomorrow so I can test this work.

**Comment by crcastle** [comment]
Nice.  I shipped the token and room name changes (#24) to dreamhouse-disco-**staging**.  Before I ship to production, I want to test end-to-end -- FB message song request through to a new track showing up on Dreamhouse Disco web page.  Can we do that tomorrow morning?

Or you might even be able to do it yourself now (I hope).  When you go to https://dreamhouse-disco-staging.herokuapp.com you should see my playlist.  I thought I had enabled this last night with #15, but forgot about OAuth token refresh.  That's now implemented with #23.

Looks like staging is registered with Travolta as `living room`.  Try to request a track for the living room via Facebook!

**Comment by thejonanshow** [comment]
Yup, sounds good.
